export const TABLE_INIT = 'TABLE_INIT';
export const TABLE_SORT_CHANGE = 'TABLE_SORT_CHANGE';
export const DATA_ADD_ITEM = 'DATA_ADD_ITEM';
export const TABLE_ADD_ITEM = 'TABLE_ADD_ITEM';
export const FETCH_PPL_SUCCESS = 'FETCH_PPL_SUCCESS';
